#!/usr/bin/env python
"""The ONE-BELT suite: a full yellow belt (15/s) of each of ~60 base-game items.

For every item, the spec is GENERATED from the game's real recipe data: the recipe
tree expands recursively down to a raw boundary (plates/stone/coal/wood arrive by
belt; every fluid ingredient becomes a boundary fluid source), then the standard
pipeline runs -- bank template first, generic solver + v3 router as fallback -- and
the verifier plus the placed-layout flow oracle grade the result. The point is to
find where the system BREAKS, so every failure mode is recorded, not skipped.

Usage:
  python scripts/belt_suite.py --gen     # write specs to corner_cases/one_belt/
  python scripts/belt_suite.py --run     # compile + verify + flow-grade everything
"""
from __future__ import annotations

import json
import re
import sys
import time
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT))

from fgr import fbsr_validation as fv                     # noqa: E402
from fgr.dsl import parse                                 # noqa: E402
from fgr.rates import BELT_FULL, RatesUnavailable, _dump  # noqa: E402

SUITE = ROOT / "corner_cases" / "one_belt"

ITEMS = [
    # intermediates
    "iron-gear-wheel", "iron-stick", "copper-cable", "electronic-circuit",
    "advanced-circuit", "processing-unit", "pipe", "engine-unit",
    "electric-engine-unit", "flying-robot-frame", "battery", "plastic-bar",
    "sulfur", "explosives", "steel-plate", "stone-brick", "concrete",
    "rocket-fuel", "low-density-structure",
    # logistics
    "transport-belt", "fast-transport-belt", "underground-belt", "splitter",
    "inserter", "fast-inserter", "long-handed-inserter", "bulk-inserter",
    "burner-inserter", "small-electric-pole", "medium-electric-pole",
    "big-electric-pole", "substation", "iron-chest", "steel-chest",
    "storage-tank", "rail",
    # machines
    "assembling-machine-1", "assembling-machine-2", "electric-furnace",
    "steel-furnace", "stone-furnace", "lab", "radar", "electric-mining-drill",
    "solar-panel", "accumulator", "steam-engine", "boiler", "pump",
    # military
    "stone-wall", "gate", "gun-turret", "firearm-magazine",
    "piercing-rounds-magazine", "grenade", "repair-pack",
    # science
    "automation-science-pack", "logistic-science-pack", "military-science-pack",
    "chemical-science-pack", "production-science-pack",
]

RAW_ITEMS = {"iron-plate", "copper-plate", "stone", "coal", "wood", "uranium-238",
             "iron-ore",      # concrete mixes ore directly
             "solid-fuel"}    # made by oil variants (recipe name != item name)
ASSEMBLER_CATS = {"crafting", "basic-crafting", "advanced-crafting",
                  "crafting-with-fluid", "electronics", "electronics-with-fluid",
                  "pressing", "organic-or-assembling"}
KIND_BY_CAT = {"smelting": "furnace", "chemistry": "chemical",
               "chemistry-or-cryogenics": "chemical"}


def _ident(name):
    s = re.sub(r"[^A-Za-z0-9_]", "_", name)
    return f"n_{s}" if s[0].isdigit() else s


def build_spec(item, dumper):
    """Expand `item`'s recipe tree to a .fgr spec (or raise ValueError with why)."""
    stages: dict[str, dict] = {}                          # item -> {kind, ings}
    fluids: set[str] = set()
    raws: set[str] = set()

    def expand(it):
        if it in stages or it in raws:
            return
        if it in RAW_ITEMS:
            raws.add(it)
            return
        r = _dump(it, "recipe", dumper)
        if not r or not r.get("ingredients"):
            raise ValueError(f"no recipe data for {it!r}")
        cat = r.get("category", "crafting")
        kind = "assembler" if cat in ASSEMBLER_CATS else KIND_BY_CAT.get(cat)
        if kind is None:
            raise ValueError(f"{it!r} needs unsupported category {cat!r}")
        ings = []
        for ing in r["ingredients"]:
            if ing.get("type") == "fluid":
                fluids.add(ing["name"])
                ings.append((ing["name"], "fluid"))
            else:
                ings.append((ing["name"], "item"))
                expand(ing["name"])
        stages[it] = {"kind": kind, "ings": ings}
    expand(item)

    lines = ["# ONE-BELT suite (generated by scripts/belt_suite.py): a full yellow",
             f"# belt (15/s) of {item}. Recipe tree from the game dumps; raws arrive",
             "# by belt, fluids by boundary source.", ""]
    for r in sorted(raws):
        lines.append(f"input     {_ident(r)} : {r}")
    for f in sorted(fluids):
        lines.append(f"fluid     {_ident(f)}_src : {f}")
    order = [it for it in _topo(stages)]
    for it in order:
        lines.append(f"{stages[it]['kind']:<9} {_ident(it)} : {it}")
    lines.append(f"output    out @ {BELT_FULL}/s")
    lines.append("")
    for it in order:
        for ing, typ in stages[it]["ings"]:
            src = f"{_ident(ing)}_src" if typ == "fluid" else _ident(ing)
            arrow = "~>" if typ == "fluid" else "->"
            lines.append(f"{src} {arrow} {_ident(it)}")
    lines.append(f"{_ident(item)} -> out")
    return "\n".join(lines) + "\n", len(stages)


def _topo(stages):
    seen, order = set(), []

    def visit(it):
        if it in seen or it not in stages:
            return
        seen.add(it)
        for ing, typ in stages[it]["ings"]:
            if typ == "item":
                visit(ing)
        order.append(it)
    for it in stages:
        visit(it)
    return order


def gen():
    dumper = fv._fbsr_dumper()
    if dumper is None:
        raise SystemExit("FBSR dumper unavailable")
    SUITE.mkdir(parents=True, exist_ok=True)
    ok = skipped = 0
    for item in ITEMS:
        try:
            text, n = build_spec(item, dumper)
        except (ValueError, RatesUnavailable) as e:
            print(f"  skip {item}: {str(e)[:90]}")
            skipped += 1
            continue
        (SUITE / f"{item.replace('-', '_')}.fgr").write_text(text)
        ok += 1
    print(f"generated {ok} specs ({skipped} skipped) -> {SUITE}")


NODE_CAP = 100          # generic-path expansions beyond this are recorded, not run
CASE_TIMEOUT = 150      # seconds per item, enforced by subprocess isolation -- one
#                         grinding negotiation must never stall the whole suite


def run_one(path: str) -> dict:
    """One item, in-process (called inside the isolation subprocess)."""
    from fgr.flow import estimate
    from fgr.generators import compile_graph
    from fgr.layout_bank import BankInapplicable, compile_bank
    from fgr.solver import solve
    from fgr.verify import verify

    p = Path(path)
    g = parse(p.read_text())
    t0 = time.time()
    row: dict = {"item": p.stem}
    mode, lay = "bank", None
    try:
        g2, plan, lay = compile_bank(g)
    except BankInapplicable as e:
        row["bank_skip"] = str(e)[:80]
        mode = "routed"
        g2, plan = solve(g)
        if len(g2.nodes) > NODE_CAP:
            row.update(mode="too-big", nodes=len(g2.nodes),
                       machines=sum(m["copies"] for m in plan["machines"].values()))
            return row
        lay = compile_graph(g2)
    rep = verify(g2, lay)
    row.update(mode=mode, entities=len(lay.entities), verify=rep.ok,
               machines=sum(m["copies"] for m in plan["machines"].values()),
               secs=round(time.time() - t0, 1))
    if rep.ok:
        est = estimate(g2, lay)
        got = sum(est["outputs_per_s"].values())
        row["flow_per_s"] = round(got, 3)
        row["meets_target"] = got >= min(plan["target_per_s"].values()) - 1e-6
    else:
        row["fails"] = "; ".join(c.name for c in rep.checks if not c.ok)[:90]
    return row


def run():
    import subprocess
    rows = []
    for p in sorted(SUITE.glob("*.fgr")):
        item = p.stem
        t0 = time.time()
        try:
            proc = subprocess.run([sys.executable, __file__, "--one", str(p)],
                                  capture_output=True, text=True,
                                  timeout=CASE_TIMEOUT)
            row = json.loads(proc.stdout.strip().splitlines()[-1]) if proc.stdout.strip()                 else {"item": item, "mode": "ERROR",
                      "error": (proc.stderr or "no output")[-160:]}
        except subprocess.TimeoutExpired:
            row = {"item": item, "mode": "TIMEOUT", "secs": CASE_TIMEOUT}
        except Exception as e:                            # noqa: BLE001
            row = {"item": item, "mode": "ERROR", "error": str(e)[:160]}
        row.setdefault("secs", round(time.time() - t0, 1))
        status = ("ok" if row.get("meets_target")
                  else row.get("mode", "?").upper() if row.get("mode") in
                  ("too-big", "TIMEOUT", "ERROR")
                  else "SHORT" if row.get("verify") else "VERIFY-FAIL")
        print(f"{item:32s} {status:11s} {row.get('mode', '?'):7s} "
              f"m={row.get('machines', 0):4d} e={row.get('entities', 0):5d} "
              f"flow={row.get('flow_per_s', '-')} ({row['secs']}s)", flush=True)
        rows.append(row)

    out = ROOT / "out" / "belt_suite_results.json"
    out.parent.mkdir(exist_ok=True)
    out.write_text(json.dumps(rows, indent=1))
    n_ok = sum(1 for r in rows if r.get("meets_target"))
    n_short = sum(1 for r in rows if r.get("verify") and not r.get("meets_target"))
    n_vfail = sum(1 for r in rows if r.get("verify") is False)
    n_big = sum(1 for r in rows if r.get("mode") == "too-big")
    n_err = sum(1 for r in rows if r.get("mode") == "ERROR")
    n_bank = sum(1 for r in rows if r.get("mode") == "bank")
    print(f"\n== {len(rows)} items: {n_ok} carry the full belt ({n_bank} as banks), "
          f"{n_short} verify but fall short, {n_vfail} fail verification, "
          f"{n_big} too big for the generic path, {n_err} error out")
    return 0


if __name__ == "__main__":
    if "--gen" in sys.argv:
        gen()
    if "--one" in sys.argv:
        try:
            print(json.dumps(run_one(sys.argv[sys.argv.index("--one") + 1])))
        except Exception as e:                            # noqa: BLE001
            print(json.dumps({"item": Path(sys.argv[-1]).stem, "mode": "ERROR",
                              "error": f"{type(e).__name__}: {e}"[:160]}))
        raise SystemExit(0)
    if "--run" in sys.argv:
        raise SystemExit(run())
