#!/usr/bin/env python
"""Generate the README gallery straight from the .fgr files, so the images and the DSL
shown can never drift: each example is compiled from its source, verified, and rendered
fresh; the markdown (DSL + image) is then written between the
``<!-- GALLERY:START -->`` / ``<!-- GALLERY:END -->`` markers in README.md.

    export FGR_FBSR_SH=/path/to/your/fbsr.sh    # needed to (re)render images
    .venv/bin/python scripts/gen_gallery.py
"""
from __future__ import annotations

import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT))

from fgr.dsl import parse                                   # noqa: E402
from fgr.layout import compile_graph                        # noqa: E402
from fgr.verify import verify                               # noqa: E402
from fgr.blueprint import to_blueprint_string               # noqa: E402

# (path, one-line blurb, inline_dsl?)  -- simple first (DSL inline), then bigger (DSL folded).
GALLERY = [
    ("examples/basic/gears.fgr",
     "The hello-world: an input chest of iron plates → an assembler making gears → an output chest, "
     "laid out as one tight aligned line.", True),
    ("examples/basic/circuits.fgr",
     "Two ingredients into one assembler — copper→cable→circuit on the spine, with the iron lane "
     "routed to the circuit's second input.", True),
    ("examples/basic/bus.fgr",
     "`A -> B, C, D` — one belt off A, tapped by an inline inserter per consumer (NO splitters). "
     "This is the canonical 'one belt feeds many machines' pattern.", True),
    ("examples/basic/merge.fgr",
     "`A, B -> C` — each source keeps its own belt and both tap C directly (a multi-tap merge, "
     "no splitter gadget).", True),
    ("examples/complex/processing_unit.fgr",
     "Reconvergent electronics (copper→cable→green→red→blue with skip-edges) **plus** sulfuric "
     "acid piped in — fluids tunnel under the belt field into the chemical/assembler fluid boxes.", False),
    ("examples/stress/deepchain_4.fgr",
     "A deep multi-stage build — clean repeating machine cells along the spine.", False),
    ("examples/stress/science_3.fgr",
     "A larger factory with furnaces and fluids, fully verified.", False),
]


def _render(stem: str, bp: str, max_w: int = 1100):
    """Render to docs/img/<stem>.png (downscaled). Returns True on success."""
    try:
        from fgr.render import RenderError, render_blueprint_string
        from PIL import Image
    except Exception:
        return False
    tmp = ROOT / "out" / f"_gallery_{stem}.png"
    try:
        render_blueprint_string(bp, tmp)
    except RenderError as ex:
        print(f"  ! render skipped for {stem}: {str(ex)[:80]}")
        return False
    im = Image.open(tmp).convert("RGB")
    if im.width > max_w:
        im = im.resize((max_w, round(im.height * max_w / im.width)), Image.LANCZOS)
    (ROOT / "docs" / "img").mkdir(parents=True, exist_ok=True)
    im.save(ROOT / "docs" / "img" / f"{stem}.png", optimize=True)
    return True


def build_block() -> str:
    out = ["<!-- GALLERY:START (generated by scripts/gen_gallery.py — do not edit by hand) -->"]
    for rel, blurb, inline in GALLERY:
        path = ROOT / rel
        stem = path.stem
        src = path.read_text().strip("\n")
        g = parse(src)
        rep = verify(g, compile_graph(g))
        assert rep.ok, f"{stem} does not verify:\n{rep.format()}"
        rendered = _render(stem, to_blueprint_string(compile_graph(g), stem))
        img = f"![{stem}](docs/img/{stem}.png)" if rendered or (ROOT / "docs/img" / f"{stem}.png").exists() else ""
        dsl = f"```text\n{src}\n```"
        out.append(f"\n### `{stem}`\n\n{blurb}\n")
        if inline:
            out.append(f"{dsl}\n\n{img}")
        else:
            out.append(f"{img}\n\n<details><summary>show the DSL</summary>\n\n{dsl}\n\n</details>")
    out.append("\n<!-- GALLERY:END -->")
    return "\n".join(out)


def main() -> int:
    readme = ROOT / "README.md"
    text = readme.read_text()
    start, end = "<!-- GALLERY:START", "<!-- GALLERY:END -->"
    block = build_block()
    if start in text and end in text:
        pre = text[: text.index(start)]
        post = text[text.index(end) + len(end):]
        readme.write_text(pre + block + post)
    else:
        print("error: GALLERY markers not found in README.md", file=sys.stderr)
        return 1
    print(f"gallery written ({len(GALLERY)} examples)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
