#!/usr/bin/env python
"""Generate the README gallery straight from the .fgr files, so the images and the DSL
shown can never drift: each example is compiled from its source, verified, and rendered
fresh; the markdown (DSL + image) is then written between the
``<!-- GALLERY:START -->`` / ``<!-- GALLERY:END -->`` markers in README.md.

    export FGR_FBSR_SH=/path/to/your/fbsr.sh    # needed to (re)render images
    .venv/bin/python scripts/gen_gallery.py
"""
from __future__ import annotations

import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT))

from fgr.dsl import parse                                   # noqa: E402
from fgr.layout import compile_graph                        # noqa: E402
from fgr.verify import verify                               # noqa: E402
from fgr.blueprint import to_blueprint_string               # noqa: E402

# (path, one-line blurb, inline_dsl?)  -- simple first (DSL inline), then bigger (DSL folded).
GALLERY = [
    ("examples/basic/gears.fgr",
     "The hello-world: an input chest of iron plates → an assembler making gears → an output chest.", True),
    ("examples/basic/circuits.fgr",
     "Two ingredients into one assembler — the compiler tunnels the iron lane *under* the cable "
     "lane with an underground belt.", True),
    ("examples/basic/bus.fgr",
     "`A -> B, C, D` is one belt off A that a splitter bus fans out to several consumers.", True),
    ("examples/basic/merge.fgr",
     "`A, B -> C` merges several sources onto a single belt (a splitter combines them).", True),
    ("examples/complex/sulfuric_acid.fgr",
     "Fluids! Water flows through **pipes** into a chemical plant; sulfuric acid comes out to a "
     "storage tank. Items ride belts, fluids ride pipes — each attaching at the machine's real "
     "fluid-box tiles.", False),
    ("examples/complex/processing_unit.fgr",
     "Reconvergent electronics: copper → cable → circuits → processing unit, with sulfuric acid "
     "piped in.", False),
    ("examples/complex/flying_robot_frame.fgr",
     "A deep multi-step build — a furnace, oil/chemical fluids (pipes + a tank), and many "
     "reconverging item belts.", False),
]


def _render(stem: str, bp: str, max_w: int = 1100):
    """Render to docs/img/<stem>.png (downscaled). Returns True on success."""
    try:
        from fgr.render import RenderError, render_blueprint_string
        from PIL import Image
    except Exception:
        return False
    tmp = ROOT / "out" / f"_gallery_{stem}.png"
    try:
        render_blueprint_string(bp, tmp)
    except RenderError as ex:
        print(f"  ! render skipped for {stem}: {str(ex)[:80]}")
        return False
    im = Image.open(tmp).convert("RGB")
    if im.width > max_w:
        im = im.resize((max_w, round(im.height * max_w / im.width)), Image.LANCZOS)
    (ROOT / "docs" / "img").mkdir(parents=True, exist_ok=True)
    im.save(ROOT / "docs" / "img" / f"{stem}.png", optimize=True)
    return True


def build_block() -> str:
    out = ["<!-- GALLERY:START (generated by scripts/gen_gallery.py — do not edit by hand) -->"]
    for rel, blurb, inline in GALLERY:
        path = ROOT / rel
        stem = path.stem
        src = path.read_text().strip("\n")
        g = parse(src)
        rep = verify(g, compile_graph(g))
        assert rep.ok, f"{stem} does not verify:\n{rep.format()}"
        rendered = _render(stem, to_blueprint_string(compile_graph(g), stem))
        img = f"![{stem}](docs/img/{stem}.png)" if rendered or (ROOT / "docs/img" / f"{stem}.png").exists() else ""
        dsl = f"```text\n{src}\n```"
        out.append(f"\n### `{stem}`\n\n{blurb}\n")
        if inline:
            out.append(f"{dsl}\n\n{img}")
        else:
            out.append(f"{img}\n\n<details><summary>show the DSL</summary>\n\n{dsl}\n\n</details>")
    out.append("\n<!-- GALLERY:END -->")
    return "\n".join(out)


def main() -> int:
    readme = ROOT / "README.md"
    text = readme.read_text()
    start, end = "<!-- GALLERY:START", "<!-- GALLERY:END -->"
    block = build_block()
    if start in text and end in text:
        pre = text[: text.index(start)]
        post = text[text.index(end) + len(end):]
        readme.write_text(pre + block + post)
    else:
        print("error: GALLERY markers not found in README.md", file=sys.stderr)
        return 1
    print(f"gallery written ({len(GALLERY)} examples)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
