#!/usr/bin/env python
"""Stage D (docs/RATES.md): simulate a compiled blueprint in the REAL game, headless,
and compare measured throughput against fgr.rates' prediction.

    scripts/get_factorio.sh                                        # once: free headless build
    .venv/bin/python scripts/simulate.py examples/basic/gears.fgr  # ~2 min game time

The pinned headless build (out/_factorio_sim/factorio, linux-x86_64) runs directly on
Linux and through docker (OrbStack / Docker Desktop, Rosetta) on macOS. Expansion mods
are disabled for pure-base determinism. Nothing touches a real game install.

Pipeline: compile the .fgr -> blueprint string -> generate a scenario whose control.lua
stamps it onto lab tiles (research unlocked, ghosts revived) and samples every output
chest's contents once per second into script-output JSON -> `factorio --scenario2map`
(bakes the scenario into a save) -> `factorio --benchmark --benchmark-ticks N` (runs
exactly N deterministic ticks, no window) -> fit the fill-rate slope, report vs the
prediction. The game is the dynamic oracle; nothing here reimplements belt physics.
"""
from __future__ import annotations

import argparse
import json
import shutil
import subprocess
import sys
import time
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT))

from fgr.dsl import parse                                   # noqa: E402
from fgr.generators import compile_graph                    # noqa: E402
from fgr.blueprint import to_blueprint_string               # noqa: E402
from fgr.verify import verify                               # noqa: E402

SCENARIO = "fgr-sim"

CONTROL_LUA = """\
-- generated by scripts/simulate.py -- do not edit
local BP = [==[
@BP@
]==]

script.on_init(function()
  -- enable every recipe WITHOUT researching techs: research grants inserter capacity
  -- bonuses (multi-item swings) that a fresh world doesn't have -- the rates model
  -- targets fresh-world hardware, so the sim must match it
  for _, r in pairs(game.forces.player.recipes) do r.enabled = true end
  local sim = game.create_surface("fgr-sim")
  sim.generate_with_lab_tiles = true
  sim.request_to_generate_chunks({0, 0}, 8)
  sim.force_generate_chunk_requests()
  local inv = game.create_inventory(1)
  local stack = inv[1]
  stack.set_stack{name = "blueprint", count = 1}
  stack.import_stack((BP:gsub("%s", "")))
  stack.build_blueprint{surface = sim, force = game.forces.player,
                        position = {0, 0}, build_mode = defines.build_mode.forced}
  for _ = 1, 6 do                       -- revive until stable (order dependencies)
    local pending = sim.find_entities_filtered{name = "entity-ghost"}
    if #pending == 0 then break end
    for _, gh in pairs(pending) do
      if gh.valid then pcall(function() gh.silent_revive() end) end
    end
  end
  inv.destroy()
  storage.samples = {}
end)

script.on_nth_tick(60, function(ev)
  local sim = game.surfaces["fgr-sim"]
  if not sim or not storage.samples then return end
  local out = {}
  for _, chest in pairs(sim.find_entities_filtered{name = "steel-chest"}) do
    local cinv = chest.get_inventory(defines.inventory.chest)
    for _, item in pairs(cinv.get_contents()) do
      out[item.name] = (out[item.name] or 0) + item.count
    end
  end
  local tanks = {}
  for _, tank in pairs(sim.find_entities_filtered{name = "storage-tank"}) do
    for fluid, amount in pairs(tank.get_fluid_contents()) do
      tanks[fluid] = (tanks[fluid] or 0) + amount
    end
  end
  storage.samples[#storage.samples + 1] = {tick = ev.tick, out = out, fluids = tanks}
  local ghosts = sim.find_entities_filtered{name = "entity-ghost"}
  helpers.write_file("fgr-sim/result.json",
    helpers.table_to_json({samples = storage.samples, unrevived_ghosts = #ghosts}),
    false)
end)
"""


SIM = ROOT / "out" / "_factorio_sim"
GAME = SIM / "factorio"                          # from scripts/get_factorio.sh
WRITE = SIM / "write"                            # private write dir (saves/scenarios/...)


class Runner:
    """Runs the pinned headless binary: directly on Linux, via docker elsewhere.
    Paths inside config.ini are the RUNNER's view (host paths on Linux, mount points
    in docker), so both modes share the same flow."""

    def __init__(self):
        if not (GAME / "bin" / "x64" / "factorio").exists():
            raise SystemExit("headless build missing -- run scripts/get_factorio.sh first")
        self.native = sys.platform.startswith("linux")
        WRITE.mkdir(parents=True, exist_ok=True)
        mods = WRITE / "mods"
        mods.mkdir(exist_ok=True)
        (mods / "mod-list.json").write_text(json.dumps({"mods": [
            {"name": "base", "enabled": True},
            {"name": "space-age", "enabled": False},
            {"name": "quality", "enabled": False},
            {"name": "elevated-rails", "enabled": False},
        ]}))
        game_dir = str(GAME) if self.native else "/opt/factorio"
        self.write_dir = str(WRITE) if self.native else "/fdata"
        (WRITE / "config.ini").write_text(
            f"[path]\nread-data={game_dir}/data\nwrite-data={self.write_dir}\n")

    def factorio(self, *args, timeout=1800):
        if self.native:
            cmd = [str(GAME / "bin" / "x64" / "factorio")]
        else:
            cmd = ["docker", "run", "--rm", "--platform", "linux/amd64",
                   "-v", f"{GAME}:/opt/factorio",
                   "-v", f"{WRITE}:/fdata",
                   "debian:stable-slim", "/opt/factorio/bin/x64/factorio"]
        cmd += ["-c", f"{self.write_dir}/config.ini", *args]
        t0 = time.time()
        p = subprocess.run(cmd, capture_output=True, text=True, timeout=timeout)
        return p, time.time() - t0


def simulate(fgr: Path, ticks: int, keep: bool = False) -> dict:
    graph = parse(fgr.read_text())
    layout = compile_graph(graph)
    rep = verify(graph, layout)
    if not rep.ok:
        raise SystemExit(f"{fgr} does not verify; not simulating a broken layout")
    bp = to_blueprint_string(layout, label=fgr.stem)

    r = Runner()
    scen = WRITE / "scenarios" / SCENARIO
    scen.mkdir(parents=True, exist_ok=True)
    (scen / "control.lua").write_text(CONTROL_LUA.replace("@BP@", bp))

    save = WRITE / "saves" / f"{SCENARIO}.zip"
    result = WRITE / "script-output" / "fgr-sim" / "result.json"
    for p in (save, result):
        if p.exists():
            p.unlink()

    p, dt = r.factorio("--scenario2map", SCENARIO, timeout=600)
    if not save.exists():
        raise SystemExit(f"scenario2map produced no save.\nstdout: {p.stdout[-1200:]}\n"
                         f"stderr: {p.stderr[-400:]}")
    print(f"  scenario2map ok ({dt:.1f}s) -> {save.name}")

    p, dt = r.factorio("--benchmark", f"{r.write_dir}/saves/{SCENARIO}.zip",
                       "--benchmark-ticks", str(ticks), timeout=1800)
    if not result.exists():
        raise SystemExit(f"benchmark wrote no result.json.\nstdout: {p.stdout[-1200:]}")
    print(f"  benchmark {ticks} ticks ok ({dt:.1f}s wall)")

    data = json.loads(result.read_text())
    if not keep:
        shutil.rmtree(scen, ignore_errors=True)
    return data


def _ols(pts):
    n = len(pts)
    sx = sum(t for t, _ in pts)
    sy = sum(v for _, v in pts)
    sxx = sum(t * t for t, _ in pts)
    sxy = sum(t * v for t, v in pts)
    d = n * sxx - sx * sx
    return (n * sxy - sx * sy) / d if d else 0.0


def fit_rates(data: dict, ticks: int) -> dict:
    """items/s per output item, with STEADINESS instead of a fixed window:

    * the fit starts 30 game-seconds after the item's first arrival (warm-up out);
    * the window is split in half and both slopes must agree within 8% -- otherwise
      the series is a transient (still ramping / regime about to change / chest
      saturating) and is labelled unsteady rather than reported as a rate;
    * fewer than ~30 items in the window -> quantization dominates -> low confidence.

    The engine is deterministic, so repeated runs are worthless as error bars; the
    honest sensitivity axis is the window itself, which the split-half test probes."""
    samples = data.get("samples", [])
    if len(samples) < 10:
        raise SystemExit(f"too few samples ({len(samples)}) -- did the build revive? "
                         f"unrevived_ghosts={data.get('unrevived_ghosts')}")
    items = sorted({k for s in samples for k in (s.get("out") or {})})
    out = {}
    for it in items:
        pts = [(s["tick"] / 60.0, (s.get("out") or {}).get(it, 0)) for s in samples]
        first = next((t for t, v in pts if v > 0), None)
        rec = {"first_item_s": round(first, 1) if first is not None else None,
               "final_count": pts[-1][1], "steady": False,
               "measured_per_s": None, "note": ""}
        if first is None:
            rec["note"] = "never produced in this run"
            out[it] = rec
            continue
        win = [(t, v) for t, v in pts if t >= first + 30]
        if len(win) < 20:
            rec["note"] = "produced too late in the run to measure"
            out[it] = rec
            continue
        half = len(win) // 2
        a, b = _ols(win[:half]), _ols(win[half:])
        slope = _ols(win)
        n_items = win[-1][1] - win[0][1]
        rec["measured_per_s"] = round(slope, 4)
        rec["window_halves_per_s"] = [round(a, 4), round(b, 4)]
        if a <= 0 or b <= 0 or abs(a - b) / max(a, b) > 0.08:
            rec["note"] = ("transient: window halves disagree "
                           f"({a:.4f} vs {b:.4f}/s) -- run longer")
        elif n_items < 30:
            rec["steady"] = True
            rec["note"] = f"steady but only {int(n_items)} items in window (quantized)"
        else:
            rec["steady"] = True
        out[it] = rec
    return out


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("source")
    ap.add_argument("--ticks", type=int, default=7200, help="game ticks (60/s)")
    ap.add_argument("--keep", action="store_true", help="keep the generated scenario")
    args = ap.parse_args()
    fgr = Path(args.source)

    print(f"# simulating {fgr} for {args.ticks} ticks ({args.ticks / 60:.0f}s game time)")
    data = simulate(fgr, args.ticks, keep=args.keep)
    measured = fit_rates(data, args.ticks)
    if data.get("unrevived_ghosts"):
        print(f"  ! {data['unrevived_ghosts']} ghosts never revived")

    graph = parse(fgr.read_text())
    layout = compile_graph(graph)
    predicted = {}
    try:
        from fgr.rates import analyze
        rrep = analyze(graph, layout)
        predicted = {"uniform": {o: v["uniform_per_s"]
                                 for o, v in rrep.get("outputs", {}).items()},
                     "sustained": rrep.get("sustained_est_per_s", {})}
    except Exception as e:                       # noqa: BLE001
        print(f"  (prediction unavailable: {e})")

    print("\n## measured (game) vs predicted (fgr rates)")
    for it, m in measured.items():
        tag = "steady" if m.get("steady") else "NOT STEADY"
        note = f" [{m['note']}]" if m.get("note") else ""
        print(f"  {it}: {m['measured_per_s']}/s ({tag}) "
              f"first at {m['first_item_s']}s, {m['final_count']} total{note}")
    if predicted:
        print(f"  predicted sustained: {predicted['sustained']}")
        print(f"  predicted uniform (machine-limited): {predicted['uniform']}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
